version: "3"

services:
  app:
    image: pedro6571/example-api:latest
    container_name: example-api
    ports:
      - "8080:8080"
    environment:
      PROFILE: "prd"
      DATABASE_URL: "jdbc:h2:mem:demo_db"
      DATABASE_USER: "sa"
      DATABASE_PASSWORD: ""
      JWT_SECRET: "UVpYnhCmlD613fHG0nshrlTVHcooM6a0GDXehTi0"
      JWT_EXPIRATION: "86400000"
      PORT: "8080"
